#!/bin/bash

# Script details
# This bash script sends all relevant jobs to a HPC running the slurm queue. To modify it to run a particular block of simulations, simply comment out
# the scenarios that are not to be tested.

#default: the main scenario presented in the manuscript
sbatch HPC_log_mig_adam_ovr00_fishfav_sens_default.slurm
sbatch HPC_log_mig_adam_ovr02_fishfav_sens_default.slurm
sbatch HPC_log_mig_adam_ovr04_fishfav_sens_default.slurm
sbatch HPC_log_mig_adam_ovr06_fishfav_sens_default.slurm
sbatch HPC_log_mig_adam_ovr08_fishfav_sens_default.slurm
sbatch HPC_log_mig_adam_ovr10_fishfav_sens_default.slurm
sbatch HPC_log_mig_adamtarg_ovr00_fishfav_sens_default.slurm
sbatch HPC_log_mig_adamtarg_ovr02_fishfav_sens_default.slurm
sbatch HPC_log_mig_adamtarg_ovr04_fishfav_sens_default.slurm
sbatch HPC_log_mig_adamtarg_ovr06_fishfav_sens_default.slurm
sbatch HPC_log_mig_adamtarg_ovr08_fishfav_sens_default.slurm
sbatch HPC_log_mig_adamtarg_ovr10_fishfav_sens_default.slurm

#catch05: when c/c_MSY = 0.5
sbatch HPC_log_mig_adam_ovr00_fishfav_sens_catch05.slurm
sbatch HPC_log_mig_adam_ovr02_fishfav_sens_catch05.slurm
sbatch HPC_log_mig_adam_ovr04_fishfav_sens_catch05.slurm
sbatch HPC_log_mig_adam_ovr06_fishfav_sens_catch05.slurm
sbatch HPC_log_mig_adam_ovr08_fishfav_sens_catch05.slurm
sbatch HPC_log_mig_adam_ovr10_fishfav_sens_catch05.slurm
sbatch HPC_log_mig_adamtarg_ovr00_fishfav_sens_catch05.slurm
sbatch HPC_log_mig_adamtarg_ovr02_fishfav_sens_catch05.slurm
sbatch HPC_log_mig_adamtarg_ovr04_fishfav_sens_catch05.slurm
sbatch HPC_log_mig_adamtarg_ovr06_fishfav_sens_catch05.slurm
sbatch HPC_log_mig_adamtarg_ovr08_fishfav_sens_catch05.slurm
sbatch HPC_log_mig_adamtarg_ovr10_fishfav_sens_catch05.slurm

#catch09: when c/c_MSY = 0.9
sbatch HPC_log_mig_adam_ovr00_fishfav_sens_catch09.slurm
sbatch HPC_log_mig_adam_ovr02_fishfav_sens_catch09.slurm
sbatch HPC_log_mig_adam_ovr04_fishfav_sens_catch09.slurm
sbatch HPC_log_mig_adam_ovr06_fishfav_sens_catch09.slurm
sbatch HPC_log_mig_adam_ovr08_fishfav_sens_catch09.slurm
sbatch HPC_log_mig_adam_ovr10_fishfav_sens_catch09.slurm
sbatch HPC_log_mig_adamtarg_ovr00_fishfav_sens_catch09.slurm
sbatch HPC_log_mig_adamtarg_ovr02_fishfav_sens_catch09.slurm
sbatch HPC_log_mig_adamtarg_ovr04_fishfav_sens_catch09.slurm
sbatch HPC_log_mig_adamtarg_ovr06_fishfav_sens_catch09.slurm
sbatch HPC_log_mig_adamtarg_ovr08_fishfav_sens_catch09.slurm
sbatch HPC_log_mig_adamtarg_ovr10_fishfav_sens_catch09.slurm

#q01: when habitat depletion = 0.1
sbatch HPC_log_mig_adamtarg_ovr00_fishfav_sens_q01.slurm
sbatch HPC_log_mig_adamtarg_ovr02_fishfav_sens_q01.slurm
sbatch HPC_log_mig_adamtarg_ovr04_fishfav_sens_q01.slurm
sbatch HPC_log_mig_adamtarg_ovr06_fishfav_sens_q01.slurm
sbatch HPC_log_mig_adamtarg_ovr08_fishfav_sens_q01.slurm
sbatch HPC_log_mig_adamtarg_ovr10_fishfav_sens_q01.slurm

#q03: when habitat depletion = 0.3
sbatch HPC_log_mig_adamtarg_ovr00_fishfav_sens_q03.slurm
sbatch HPC_log_mig_adamtarg_ovr02_fishfav_sens_q03.slurm
sbatch HPC_log_mig_adamtarg_ovr04_fishfav_sens_q03.slurm
sbatch HPC_log_mig_adamtarg_ovr06_fishfav_sens_q03.slurm
sbatch HPC_log_mig_adamtarg_ovr08_fishfav_sens_q03.slurm
sbatch HPC_log_mig_adamtarg_ovr10_fishfav_sens_q03.slurm

#r01: when habitat recovery = 0.1
sbatch HPC_log_mig_adamtarg_ovr00_fishfav_sens_r01.slurm
sbatch HPC_log_mig_adamtarg_ovr02_fishfav_sens_r01.slurm
sbatch HPC_log_mig_adamtarg_ovr04_fishfav_sens_r01.slurm
sbatch HPC_log_mig_adamtarg_ovr06_fishfav_sens_r01.slurm
sbatch HPC_log_mig_adamtarg_ovr08_fishfav_sens_r01.slurm
sbatch HPC_log_mig_adamtarg_ovr10_fishfav_sens_r01.slurm

#r03: when habitat recovery = 0.3
sbatch HPC_log_mig_adamtarg_ovr00_fishfav_sens_r03.slurm
sbatch HPC_log_mig_adamtarg_ovr02_fishfav_sens_r03.slurm
sbatch HPC_log_mig_adamtarg_ovr04_fishfav_sens_r03.slurm
sbatch HPC_log_mig_adamtarg_ovr06_fishfav_sens_r03.slurm
sbatch HPC_log_mig_adamtarg_ovr08_fishfav_sens_r03.slurm
sbatch HPC_log_mig_adamtarg_ovr10_fishfav_sens_r03.slurm

#targdam: when the targeted species is also subject to damage
sbatch HPC_log_mig_adam_ovr00_fishfav_sens_targdam.slurm
sbatch HPC_log_mig_adam_ovr02_fishfav_sens_targdam.slurm
sbatch HPC_log_mig_adam_ovr04_fishfav_sens_targdam.slurm
sbatch HPC_log_mig_adam_ovr06_fishfav_sens_targdam.slurm
sbatch HPC_log_mig_adam_ovr08_fishfav_sens_targdam.slurm
sbatch HPC_log_mig_adam_ovr10_fishfav_sens_targdam.slurm
sbatch HPC_log_mig_adamtarg_ovr00_fishfav_sens_targdam.slurm
sbatch HPC_log_mig_adamtarg_ovr02_fishfav_sens_targdam.slurm
sbatch HPC_log_mig_adamtarg_ovr04_fishfav_sens_targdam.slurm
sbatch HPC_log_mig_adamtarg_ovr06_fishfav_sens_targdam.slurm
sbatch HPC_log_mig_adamtarg_ovr08_fishfav_sens_targdam.slurm
sbatch HPC_log_mig_adamtarg_ovr10_fishfav_sens_targdam.slurm

#nspec25: when there are 25 species per class
sbatch HPC_log_mig_adam_ovr00_fishfav_sens_nspec25.slurm
sbatch HPC_log_mig_adam_ovr02_fishfav_sens_nspec25.slurm
sbatch HPC_log_mig_adam_ovr04_fishfav_sens_nspec25.slurm
sbatch HPC_log_mig_adam_ovr06_fishfav_sens_nspec25.slurm
sbatch HPC_log_mig_adam_ovr08_fishfav_sens_nspec25.slurm
sbatch HPC_log_mig_adam_ovr10_fishfav_sens_nspec25.slurm
sbatch HPC_log_mig_adamtarg_ovr00_fishfav_sens_nspec25.slurm
sbatch HPC_log_mig_adamtarg_ovr02_fishfav_sens_nspec25.slurm
sbatch HPC_log_mig_adamtarg_ovr04_fishfav_sens_nspec25.slurm
sbatch HPC_log_mig_adamtarg_ovr06_fishfav_sens_nspec25.slurm
sbatch HPC_log_mig_adamtarg_ovr08_fishfav_sens_nspec25.slurm
sbatch HPC_log_mig_adamtarg_ovr10_fishfav_sens_nspec25.slurm

#m01: when the migration rate = 0.1
sbatch HPC_log_mig_adam_ovr00_fishfav_sens_m01.slurm
sbatch HPC_log_mig_adam_ovr02_fishfav_sens_m01.slurm
sbatch HPC_log_mig_adam_ovr04_fishfav_sens_m01.slurm
sbatch HPC_log_mig_adam_ovr06_fishfav_sens_m01.slurm
sbatch HPC_log_mig_adam_ovr08_fishfav_sens_m01.slurm
sbatch HPC_log_mig_adam_ovr10_fishfav_sens_m01.slurm
sbatch HPC_log_mig_adamtarg_ovr00_fishfav_sens_m01.slurm
sbatch HPC_log_mig_adamtarg_ovr02_fishfav_sens_m01.slurm
sbatch HPC_log_mig_adamtarg_ovr04_fishfav_sens_m01.slurm
sbatch HPC_log_mig_adamtarg_ovr06_fishfav_sens_m01.slurm
sbatch HPC_log_mig_adamtarg_ovr08_fishfav_sens_m01.slurm
sbatch HPC_log_mig_adamtarg_ovr10_fishfav_sens_m01.slurm

#m09: when the migration rate = 0.9
sbatch HPC_log_mig_adam_ovr00_fishfav_sens_m09.slurm
sbatch HPC_log_mig_adam_ovr02_fishfav_sens_m09.slurm
sbatch HPC_log_mig_adam_ovr04_fishfav_sens_m09.slurm
sbatch HPC_log_mig_adam_ovr06_fishfav_sens_m09.slurm
sbatch HPC_log_mig_adam_ovr08_fishfav_sens_m09.slurm
sbatch HPC_log_mig_adam_ovr10_fishfav_sens_m09.slurm
sbatch HPC_log_mig_adamtarg_ovr00_fishfav_sens_m09.slurm
sbatch HPC_log_mig_adamtarg_ovr02_fishfav_sens_m09.slurm
sbatch HPC_log_mig_adamtarg_ovr04_fishfav_sens_m09.slurm
sbatch HPC_log_mig_adamtarg_ovr06_fishfav_sens_m09.slurm
sbatch HPC_log_mig_adamtarg_ovr08_fishfav_sens_m09.slurm
sbatch HPC_log_mig_adamtarg_ovr10_fishfav_sens_m09.slurm