# Script details ####

# Script of simulation parameters used in 
# XXXX

# Parameters ####

## Simulation ####

simulation.name <- "log_mig_adamtarg_ovr04_fishfav_sens_catch05tdam"
n.sims <- 50 # Number of simulations
n.time <- 150 # Length of simulations
n.species <- 10 # Number of species drawn from each class
n.patches <- 20 # Number of patches in seascape
n.catch.ints <- 4 # Number of catch intervals to explore
catch.divisor <- 1 # Number to divide MSY calculation by (suitable for growth functions in which the logistic growth calculation of MSY is too high or low)
start.pop <- 0.99 # All species (targeted and non-targeted) starting abundance as a fraction of K

## Habitat ####

# Non-targeted species habitat options 
# 1.x = habitat generated by auto-regressive model
## 1.1 = all non-targeted species share the same habitat
## 1.2 = all non-targeted classes share the same habitat
## 1.3 = no non-targeted species share habitat
## 1.4 = Improved 1.3: random starting patch, other fixes
# 2.x = habitat specified manually
## 2.1 = all non-targeted species share the same habitat
# 3.x = habitat generated by function in response to environmental conditions
## 3.1 = single variable linear functional response
## 3.2 = double variable linear functional response
# 4.x = habitat generated by multivariate normal distribution
## 4.1 = all species generated by multivariate normal distribution
## 4.2 = generate non-targeted species based on existing targeted species (multivariate normal distribution)
## 4.3 = generate non-targeted species based on existing manually specified targeted species (multivariate normal distribution)
# 5.x = non-targeted species overlap targeted species as specified
## 5.1 = non-targeted species overlap targeted species as specified
# 7.x = random patches but with prescribed overlap
## 7.1 = random patches but with prescribed overlap

non.targ.habitat.option <- 7.1

# Option 1 parameterisation
# Habitat parameters
habitat.phi <- 1
habitat.dev.mean <- 0
habitat.dev.sd <- 0.1
habitat.first.patch.k <- 0.5 # The K value of the first patch. If 0, there may be some species that have k = 0 in all patches, which breaks the simulation

# Option 2 parameterisation
non.targ.manual.habitat.value <- 1 # If using 2.1, k value of each patch

# Option 3 parameterisation
## 3.1
gradient.lims <- c(0,1) # Upper and lower limits of environmental gradient
env.gradient <- seq(gradient.lims[1],gradient.lims[2],length.out=n.patches) # Values of environmental gradient
response.min <- -3 # Specify minimum value relationship can be drawn as
response.max <- 3 # Specify maximum value relationship can be drawn as
## 3.2
gradient.lims.1 <- c(0,1) # Upper and lower limits of environmental gradient
gradient.lims.2 <- c(0,1) # Upper and lower limits of environmental gradient
env.gradient.1 <- seq(gradient.lims.1[1],gradient.lims.1[2],length.out=n.patches) # Values of environmental gradient
env.gradient.2 <- seq(gradient.lims.2[1],gradient.lims.2[2],length.out=n.patches) # Values of environmental gradient
response.min.1 <- -3 # Specify minimum value relationship can be drawn as
response.max.1 <- 3 # Specify maximum value relationship can be drawn as
response.min.2 <- -3 # Specify minimum value relationship can be drawn as
response.max.2 <- 3 # Specify maximum value relationship can be drawn as

# Option 4 parameterisation
## 4.1
#habitat.correlation <- 0 # Specify correlation
hab.mean.nt <- 0 # Specify mean habitat
## 4.2
habitat.mean <- 0
habitat.sd <- 1
habitat.correlation <- -0.50

# Option 5 parameterisation
overlap <- 0.4 # Overlap must be in 5ths if 10 patches and 50% proportion present etc.

# Option 7 parameterisation
factor.val <- 1 # Leave as 1 if don't know what doing
n.occupied <- n.patches/2 # How many patches are occupied by a single species 
random.overlap <- 0.4 # Proportion of overlap non-targeted species have with fishery

# Targeted species habitat options 
# 1.x = habitat generated by auto-regressive model
## 1.1 = targeted species given same habitat as all non-targeted species
## 1.2 = targeted species given same habitat as particular non-targeted class
## 1.3 = targeted species given unique habitat
## 1.4 = Improved 1.3: random starting patch, other fixes
# 2.x = habitat specified manually
## 2.1 = share the same habitat as non-targeted species
# 3.x = habitat generated by function in response to environmental conditions
## 3.1 = single variable linear functional response
## 3.2 = double variable linear functional response
# 4.x = habitat generated by multivariate normal distribution
## 4.1 = Uses habitat generated from settings for non-targeted species
## 4.2 = Uses habitat generated from settings for non-targeted species
## 4.3 = Manually specified targeted species
# 5.1 = Same as 4.3. Use those options
# 7.x = random patches but with prescribed overlap (inherets all settings from non.targeted.species setttings)
## 7.1 = random patches but with prescribed overlap (inherets all settings from non.targeted.species setttings)

targ.habitat.option <- 7.1

# Option 2 parameterisation
targ.manual.habitat.value <- 1 # If using 2.1, k value of each patch

# Option 3 parameterisation
## Inherits all settings from non-targeted species habitat parameterisation above

# Option 4 parameterisation
## 4.3
proportion.present <- 0.5 # Proportion of patches targeted species is present in
k.when.present <- 1 # Targeted species K in patches where present

## Targeted species ####

# Targeted species options
# 1 = targeted species parameters are set manually
# 2 = targeted species is selected randomly from any class
# 3 = targeted species is selected randomly from particular class
# 4 = targeted species is perfectly average species from particular class
targ.spec.option <- 1

# Targeted species parameters for `targ.spec.option <- 1`
targeted.class <- "Malacostraca"
targeted.species <- "Malacostraca 0"
targeted.r <- 0.818 # Intrinsic reproduction rate
targeted.q <- 0.109 # Catchability
targeted.p <- 10 # Price
targeted.c <- 1 # Cost per unit effort
targeted.m <- 0.3 # Migration rate

## Growth function ####

# Non-targeted species growth function
# 1 = Logistic growth based on within patch population size only
# 2 = Logistic growth with common pool "larval" dispersal (Takashina version)
# 3 = Logistic growth with common pool "larval" dispersal (flawed (?) Erm version)
# 4 = Beverton-Holt growth with common pool "larval" dispersal (Holden version)
# 5 = Allee effect (Roques version) based on within patch population size only
# 6 = Beverton-Holt growth with common pool "larval" dispersal (Holden version with seascape.k in denominator)
# 7 = Beverton-Holt growth with common pool "larval" dispersal (current best form)
# 8 = Logistic growth with common pool "larval" dispersal (Sala version version)
# 9 = Exponential growth with hockey stick
non.targeted.growth.option <- 1

# Option 4/6 parameterisation
global.survival <- 0.8 # Fraction surviving per time step

# Option 5 parameterisation
non.targeted.a <- 0.05 # Fraction of K that constitutes Allee threshold

# Targeted species growth function
# 1 = Logistic growth based on within patch population size only
# 2 = Logistic growth with common pool "larval" dispersal (Takashina version)
# 3 = Logistic growth with common pool "larval" dispersal (flawed (?) Erm version)
# 4 = Beverton-Holt growth with common pool "larval" dispersal (Holden version)
# 5 = Allee effect (Roques version) based on within patch population size only. Currently means that Allee effect is sensitive to K of patch, leading to absurdity that each patch has a different Allee threshold
# 6 = Beverton-Holt growth with common pool "larval" dispersal (Holden version with seascape.k in denominator)
# 7 = Beverton-Holt growth with common pool "larval" dispersal (current best form)
# 8 = Logistic growth with common pool "larval" dispersal (Sala version version)
# 9 = Exponential growth with hockey stick
targeted.growth.option <- 1

# Option 5 parameterisation
targeted.a <- 0.05 # Fraction of K that constitutes Allee threshold

## Migration ####

# Migration rate
# 1 = Manually set identical migration rates (m) for all non-targeted species
# 2 = Migration rates drawn from a uniform distribution with specified parameters
mig.rate.option <- 1
custom.m <- 0.3 # Specify m if using option 1
migration.min.m <- 0 # Specify minimum m if using option 2
migration.max.m <- 1 # Specify maximum m if using option 2

# Migration function
# 1 = No migration
# 2 = Spatially implicit random diffusion based on patch habitat quality
# 3 = Spatially implicit random diffusion based on patch size
mig.option <- 2

## Management and MPAs ####

# Effort management options
# 1 = open access dynamics according to Gordon model outside of MPAs
# 2 = efficient effort allocation outside of MPA for catch target
# 3 = blanket effort allocation outside of MPA for catch target
man.option <- 2

# MPA management options
# 1 = MPAs are assigned to patches randomly
# 2 = MPAs are assigned to patches with highest aggregate habitat value for non-targeted species
# 3 = MPAs are assigned to patches with lowest habitat value to targeted species
MPA.option <- 3

# Management/MPA cost parameters
mpa.init.cost <- 10 # MPA initial cost
mpa.ongoing.cost <- 5 # MPA ongoing cost per patch with MPA
man.init.cost <- 20 # Effort management initial cost per patch with management
man.ongoing.cost <- 10 # Effort management ongoing cost

## Habitat damage ####

# Habitat damage options
# 1 = RBS model but applied to K
# 2 = Multiplicative model (i.e. a fraction of the difference between pristine and current K restores each time)
damage.option <- 2

# Parameters
dep.Kt <- 0.2 # Fractional depletion rate per trawl pass for targeted species
rep.Kt <- 0.2 # Intrinsic recovery rate of habitat for targeted species

dep.K <- 0.2 # Fractional depletion rate per trawl pass
rep.K <- 0.2 # Intrinsic recovery rate of habitat

## Conservation score ####

ext.thresh <- 0.05 # Proportion of population below which population is marked as "extinct" so far as geometric mean calculation is concerned

## IUCN Red List status ####
# 1 = standard categories (CR = 90% reduction, E = 70%, V = 50%)
# 2 = conservative categories (CR = 80% reduction, E = 50%, V = 30%)
IUCN.option <- 1

## Chaos management ####

# Chaos management options
# 1 = Chaotic dynamics are not curtailed in any way
# 2 = Species with r above a specified threshold will have their r value reduced to that threshold
# 3 = All species' time sensitive values will be divided by a specified number (in effect shortening the time step that r, m etc. represents)
chaos.man.option <- 2

# Option 2 parameterisation
r.thresh.min <- 0.25 # All species with an r below this number will have their rs raised to the threshold
r.thresh.max <- 2 # All species with an r above this number will have their rs lowered to the threshold. 2.569944 is approximately where true chaos begins to manifest according to theory

# Option 3 parameterisation
par.division <- 2

## Carbon ####

carbon.start <- 1 # Starting carbon in each patch
pdepth <- 0.0244 # Penetration depth of trawl gear
pcred <-  0.87 # Fraction of carbon resettling locally
plab <- 0.7 # Fraction of carbon labile. Mud = 0.7; gravel = 0.286; sand = 0.04
carb.k <- 1 # First-order degradation rate constant. North Pacific = 1.67; South Pacific = 3.84; Atlantic = 1; Indian = 4.76; Mediterranean = 12.3; Arctic = 0.275; Gulf of Mexico and Caribbean = 16.8
carb.t <- 1 # Time in the degradation equation. Must be left at 1
rs <- 0.07/100 # Natural sediment accumulation rate
eps <- 0.3